name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3      
        
      - uses: azure/docker-login@v1
        with:
          login-server: kingkong2.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          cd app
          docker build -t kingkong2.azurecr.io/js-app:${{ github.sha }} .
          docker push kingkong2.azurecr.io/js-app:${{ github.sha }}
